//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/anthonyrey/Desktop/Interpreter1/Expr.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class ExprLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		LPAR=1, RPAR=2, NAME=3, COMMENTS=4, STRING=5, EMPTY_LIST=6, INT=7, FLOATING=8, 
		WS=9;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"LPAR", "RPAR", "NAME", "COMMENTS", "STRING", "EMPTY_LIST", "INT", "FLOATING", 
		"WS"
	};


	public ExprLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ExprLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "LPAR", "RPAR", "NAME", "COMMENTS", "STRING", "EMPTY_LIST", "INT", 
		"FLOATING", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Expr.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ExprLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\v', 'U', '\b', '\x1', '\x4', '\x2', '\t', '\x2', '\x4', 
		'\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', 
		'\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', 
		'\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x6', '\x4', 
		'\x1B', '\n', '\x4', '\r', '\x4', '\xE', '\x4', '\x1C', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', '#', '\n', '\x5', 
		'\f', '\x5', '\xE', '\x5', '&', '\v', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\a', '\x6', '/', '\n', '\x6', '\f', '\x6', '\xE', '\x6', '\x32', '\v', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\a', '\a', 
		'\x38', '\n', '\a', '\f', '\a', '\xE', '\a', ';', '\v', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x6', '\b', '@', '\n', '\b', '\r', '\b', '\xE', 
		'\b', '\x41', '\x3', '\t', '\x6', '\t', '\x45', '\n', '\t', '\r', '\t', 
		'\xE', '\t', '\x46', '\x3', '\t', '\x3', '\t', '\x6', '\t', 'K', '\n', 
		'\t', '\r', '\t', '\xE', '\t', 'L', '\x3', '\n', '\x6', '\n', 'P', '\n', 
		'\n', '\r', '\n', '\xE', '\n', 'Q', '\x3', '\n', '\x3', '\n', '\x5', '$', 
		'\x30', '\x39', '\x2', '\v', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x3', '\x2', '\x5', '\x6', '\x2', '\'', '\'', ',', '\x31', '\x43', 
		'\\', '\x63', '|', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\v', '\f', 
		'\xF', '\xF', '\"', '\"', '\x2', '\\', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x3', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x5', '\x17', '\x3', '\x2', '\x2', '\x2', '\a', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '\t', '\x1E', '\x3', '\x2', '\x2', '\x2', 
		'\v', ',', '\x3', '\x2', '\x2', '\x2', '\r', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '?', '\x3', '\x2', '\x2', '\x2', '\x11', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\x13', 'O', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'\x16', '\a', '*', '\x2', '\x2', '\x16', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'\x17', '\x18', '\a', '+', '\x2', '\x2', '\x18', '\x6', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '\x1B', '\t', '\x2', '\x2', '\x2', '\x1A', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x1B', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'\x1C', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\b', '\x3', '\x2', '\x2', '\x2', '\x1E', '\x1F', 
		'\a', '=', '\x2', '\x2', '\x1F', ' ', '\a', '=', '\x2', '\x2', ' ', '$', 
		'\x3', '\x2', '\x2', '\x2', '!', '#', '\v', '\x2', '\x2', '\x2', '\"', 
		'!', '\x3', '\x2', '\x2', '\x2', '#', '&', '\x3', '\x2', '\x2', '\x2', 
		'$', '%', '\x3', '\x2', '\x2', '\x2', '$', '\"', '\x3', '\x2', '\x2', 
		'\x2', '%', '\'', '\x3', '\x2', '\x2', '\x2', '&', '$', '\x3', '\x2', 
		'\x2', '\x2', '\'', '(', '\a', '=', '\x2', '\x2', '(', ')', '\a', '=', 
		'\x2', '\x2', ')', '*', '\x3', '\x2', '\x2', '\x2', '*', '+', '\b', '\x5', 
		'\x2', '\x2', '+', '\n', '\x3', '\x2', '\x2', '\x2', ',', '\x30', '\a', 
		'$', '\x2', '\x2', '-', '/', '\v', '\x2', '\x2', '\x2', '.', '-', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x32', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x30', '.', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\x33', '\x3', '\x2', '\x2', '\x2', '\x32', '\x30', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x34', '\a', '$', '\x2', '\x2', '\x34', 
		'\f', '\x3', '\x2', '\x2', '\x2', '\x35', '\x39', '\x5', '\x3', '\x2', 
		'\x2', '\x36', '\x38', '\a', '\"', '\x2', '\x2', '\x37', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\x38', ';', '\x3', '\x2', '\x2', '\x2', '\x39', 
		':', '\x3', '\x2', '\x2', '\x2', '\x39', '\x37', '\x3', '\x2', '\x2', 
		'\x2', ':', '<', '\x3', '\x2', '\x2', '\x2', ';', '\x39', '\x3', '\x2', 
		'\x2', '\x2', '<', '=', '\x5', '\x5', '\x3', '\x2', '=', '\xE', '\x3', 
		'\x2', '\x2', '\x2', '>', '@', '\t', '\x3', '\x2', '\x2', '?', '>', '\x3', 
		'\x2', '\x2', '\x2', '@', '\x41', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'?', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\x3', '\x2', '\x2', 
		'\x2', '\x42', '\x10', '\x3', '\x2', '\x2', '\x2', '\x43', '\x45', '\t', 
		'\x3', '\x2', '\x2', '\x44', '\x43', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x46', '\x3', '\x2', '\x2', '\x2', '\x46', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\x46', 'G', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\x3', '\x2', 
		'\x2', '\x2', 'H', 'J', '\a', '\x30', '\x2', '\x2', 'I', 'K', '\t', '\x3', 
		'\x2', '\x2', 'J', 'I', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\x3', '\x2', 
		'\x2', '\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\x3', '\x2', 
		'\x2', '\x2', 'M', '\x12', '\x3', '\x2', '\x2', '\x2', 'N', 'P', '\t', 
		'\x4', '\x2', '\x2', 'O', 'N', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\x3', 
		'\x2', '\x2', '\x2', 'Q', 'O', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\x3', 
		'\x2', '\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\b', 
		'\n', '\x2', '\x2', 'T', '\x14', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', 
		'\x1C', '$', '\x30', '\x39', '\x41', '\x46', 'L', 'Q', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
